### ISSUE TITLE
Unchanged from Default 'React App' Page Title and Icon

### ISSUE THREAD

**Issue by MagusWyvern** [pydeep9026/foodoun#1]
In the Web App, it appears that the title has not been changed from the default 'React App' placeholder. In the same vein, the icon is also from a React's app default placeholder.

![image](https://user-images.githubusercontent.com/72914828/233219514-01df6759-c9fb-4147-9581-21764faafb48.png)

Is this intentional?

**Comment by pydeep9026** [comment]
No , just forgot to change it.
